import React, { useEffect, useState } from 'react';
import {
  Box,
  Heading,
  VStack,
  Card,
  CardBody,
  Button,
  useToast,
  Select,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Textarea,
  HStack,
  Badge,
  Text,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  IconButton,
} from '@chakra-ui/react';
import { DownloadIcon, ChevronDownIcon } from '@chakra-ui/icons';
import { Layout } from '../components/Layout';
import { useAuth } from '../contexts/AuthContext';
import { supabase } from '../config/supabase';
import type { TimesheetDayType } from '../types';

interface TimesheetType {
  id: string;
  employee_id: string;
  month: number;
  year: number;
  days: Record<number, { type: TimesheetDayType; description: string }>;
  status: 'Draft' | 'Submitted';
  submitted_at?: string;
}

const Timesheet: React.FC = () => {
  const { currentUser, userData } = useAuth();
  const [month, setMonth] = useState(new Date().getMonth());
  const [year, setYear] = useState(new Date().getFullYear());
  const [timesheet, setTimesheet] = useState<TimesheetType | null>(null);
  const [loading, setLoading] = useState(false);
  const toast = useToast();

  const daysInMonth = new Date(year, month + 1, 0).getDate();

  useEffect(() => {
    fetchTimesheet();
  }, [month, year, currentUser]);

  const fetchTimesheet = async () => {
    if (!currentUser) return;

    try {
      const { data, error } = await supabase
        .from('timesheets')
        .select('*')
        .eq('employee_id', currentUser.id)
        .eq('month', month)
        .eq('year', year)
        .single();

      if (error && error.code !== 'PGRST116') {
        throw error;
      }

      if (data) {
        setTimesheet(data);
      } else {
        // Create a new timesheet object without id (let database generate it)
        const newTimesheet: TimesheetType = {
          id: '', // Will be generated by database
          employee_id: currentUser.id,
          month,
          year,
          days: {},
          status: 'Draft',
        };
        setTimesheet(newTimesheet);
      }
    } catch (error) {
      console.error('Error fetching timesheet:', error);
    }
  };

  const handleDayTypeChange = (day: number, type: TimesheetDayType) => {
    if (!timesheet) return;

    setTimesheet({
      ...timesheet,
      days: {
        ...timesheet.days,
        [day]: {
          type,
          description: timesheet.days[day]?.description || '',
        },
      },
    });
  };

  const handleDescriptionChange = (day: number, description: string) => {
    if (!timesheet) return;

    setTimesheet({
      ...timesheet,
      days: {
        ...timesheet.days,
        [day]: {
          type: timesheet.days[day]?.type || 'Full Day',
          description,
        },
      },
    });
  };

  const handleSave = async (submit: boolean = false) => {
    if (!timesheet || !currentUser) return;

    setLoading(true);

    try {
      const updatedTimesheet: any = {
        employee_id: timesheet.employee_id,
        month: timesheet.month,
        year: timesheet.year,
        days: timesheet.days,
        status: submit ? ('Submitted' as const) : ('Draft' as const),
        ...(submit && { submitted_at: new Date().toISOString() }),
      };

      // Only include id if it exists (for updates)
      if (timesheet.id) {
        updatedTimesheet.id = timesheet.id;
      }

      const { error } = await supabase
        .from('timesheets')
        .upsert(updatedTimesheet, {
          onConflict: 'employee_id,month,year',
        });

      if (error) throw error;

      toast({
        title: submit ? 'Timesheet submitted successfully' : 'Timesheet saved as draft',
        status: 'success',
        duration: 3000,
      });

      await fetchTimesheet();
    } catch (error: any) {
      toast({
        title: 'Error saving timesheet',
        description: error.message,
        status: 'error',
        duration: 5000,
      });
    } finally {
      setLoading(false);
    }
  };

  const handleUndoSubmission = async () => {
    if (!timesheet || !currentUser) return;

    setLoading(true);

    try {
      const updatedTimesheet: any = {
        employee_id: timesheet.employee_id,
        month: timesheet.month,
        year: timesheet.year,
        days: timesheet.days,
        status: 'Draft' as const,
        submitted_at: null,
      };

      if (timesheet.id) {
        updatedTimesheet.id = timesheet.id;
      }

      const { error } = await supabase
        .from('timesheets')
        .upsert(updatedTimesheet, {
          onConflict: 'employee_id,month,year',
        });

      if (error) throw error;

      toast({
        title: 'Submission undone successfully',
        description: 'You can now edit your timesheet',
        status: 'success',
        duration: 3000,
      });

      await fetchTimesheet();
    } catch (error: any) {
      toast({
        title: 'Error undoing submission',
        description: error.message,
        status: 'error',
        duration: 5000,
      });
    } finally {
      setLoading(false);
    }
  };

  const canUndoSubmission = () => {
    if (!timesheet || timesheet.status !== 'Submitted' || !timesheet.submitted_at) {
      return false;
    }

    // Calculate the end of the timesheet period (last day of the month)
    const periodEnd = new Date(year, month + 1, 0);
    // Add 7 days to the period end
    const undoDeadline = new Date(periodEnd);
    undoDeadline.setDate(undoDeadline.getDate() + 7);

    const now = new Date();
    return now <= undoDeadline;
  };

  const handleDownload = async (format: 'pdf' | 'csv') => {
    if (!timesheet || !currentUser || !userData) return;

    try {
      // Get manager details if available
      let managerName = 'N/A';
      if (userData.managerId) {
        const { data: managerData } = await supabase
          .from('users')
          .select('display_name, email')
          .eq('id', userData.managerId)
          .single();

        if (managerData) {
          managerName = managerData.display_name || managerData.email;
        }
      }

      if (format === 'csv') {
        downloadCSV(managerName);
      } else {
        downloadPDF(managerName);
      }
    } catch (error: any) {
      toast({
        title: 'Error downloading timesheet',
        description: error.message,
        status: 'error',
        duration: 5000,
      });
    }
  };

  const downloadCSV = (managerName: string) => {
    if (!timesheet || !userData) return;

    const monthName = months[month];
    const employeeName = userData.displayName || userData.email;

    let csvContent = 'data:text/csv;charset=utf-8,';
    csvContent += `Employee Name,${employeeName}\n`;
    csvContent += `Manager Name,${managerName}\n`;
    csvContent += `Month,${monthName} ${year}\n`;
    csvContent += `Status,${timesheet.status}\n`;
    csvContent += `\n`;
    csvContent += 'Date,Day,Type,Description\n';

    for (let day = 1; day <= daysInMonth; day++) {
      const dayData = timesheet.days[day];
      const dayName = getDayName(day);
      const type = dayData?.type || 'Full Day';
      const description = dayData?.description || '';
      csvContent += `${day},${dayName},${type},"${description.replace(/"/g, '""')}"\n`;
    }

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `timesheet_${monthName}_${year}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    toast({
      title: 'Timesheet downloaded',
      description: 'CSV file has been saved',
      status: 'success',
      duration: 3000,
    });
  };

  const downloadPDF = (managerName: string) => {
    if (!timesheet || !userData) return;

    // For PDF, we'll create a printable HTML view that can be printed to PDF
    const monthName = months[month];
    const employeeName = userData.displayName || userData.email;

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast({
        title: 'Popup blocked',
        description: 'Please allow popups to download PDF',
        status: 'error',
        duration: 5000,
      });
      return;
    }

    let tableRows = '';
    for (let day = 1; day <= daysInMonth; day++) {
      const dayData = timesheet.days[day];
      const dayName = getDayName(day);
      const type = dayData?.type || 'Full Day';
      const description = dayData?.description || '';
      const isWeekendDay = isWeekend(day);
      tableRows += `
        <tr style="background-color: ${isWeekendDay ? '#ffe0e0' : 'white'};">
          <td style="border: 1px solid #ddd; padding: 8px;">${day}</td>
          <td style="border: 1px solid #ddd; padding: 8px;">${dayName}</td>
          <td style="border: 1px solid #ddd; padding: 8px;">${type}</td>
          <td style="border: 1px solid #ddd; padding: 8px;">${description}</td>
        </tr>
      `;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Timesheet - ${monthName} ${year}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #333; }
            .info { margin-bottom: 20px; }
            .info p { margin: 5px 0; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background-color: #667eea; color: white; padding: 12px; text-align: left; border: 1px solid #ddd; }
            td { border: 1px solid #ddd; padding: 8px; }
            @media print {
              body { padding: 0; }
            }
          </style>
        </head>
        <body>
          <h1>Timesheet - ${monthName} ${year}</h1>
          <div class="info">
            <p><strong>Employee Name:</strong> ${employeeName}</p>
            <p><strong>Manager Name:</strong> ${managerName}</p>
            <p><strong>Status:</strong> ${timesheet.status}</p>
          </div>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Day</th>
                <th>Type</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              ${tableRows}
            </tbody>
          </table>
          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 100);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();

    toast({
      title: 'Print dialog opened',
      description: 'Save as PDF from the print dialog',
      status: 'info',
      duration: 3000,
    });
  };

  const months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];

  const getDayName = (day: number) => {
    const date = new Date(year, month, day);
    return date.toLocaleDateString('en-US', { weekday: 'short' });
  };

  const isWeekend = (day: number) => {
    const date = new Date(year, month, day);
    const dayOfWeek = date.getDay();
    return dayOfWeek === 0 || dayOfWeek === 6;
  };

  return (
    <Layout>
      <VStack spacing={6} align="stretch">
        <Box display="flex" justifyContent="space-between" alignItems="center" flexWrap="wrap" gap={4}>
          <Heading size="lg" color="white">Timesheet</Heading>
          <HStack spacing={3}>
            {timesheet?.status === 'Submitted' && (
              <Badge colorScheme="green" fontSize="md" px={3} py={1}>
                Submitted
              </Badge>
            )}
            <Menu>
              <MenuButton
                as={Button}
                rightIcon={<ChevronDownIcon />}
                leftIcon={<DownloadIcon />}
                size="sm"
                variant="outline"
                color="whiteAlpha.900"
                borderColor="rgba(255, 255, 255, 0.2)"
                _hover={{ bg: 'rgba(255, 255, 255, 0.1)', borderColor: 'brand.400' }}
              >
                Download
              </MenuButton>
              <MenuList bg="#1a1a1a" borderColor="rgba(255, 255, 255, 0.2)">
                <MenuItem
                  onClick={() => handleDownload('csv')}
                  bg="#1a1a1a"
                  _hover={{ bg: 'rgba(255, 255, 255, 0.1)' }}
                  color="white"
                >
                  Download as CSV
                </MenuItem>
                <MenuItem
                  onClick={() => handleDownload('pdf')}
                  bg="#1a1a1a"
                  _hover={{ bg: 'rgba(255, 255, 255, 0.1)' }}
                  color="white"
                >
                  Download as PDF
                </MenuItem>
              </MenuList>
            </Menu>
          </HStack>
        </Box>

        <Card bg="rgba(255, 255, 255, 0.05)" borderColor="rgba(255, 255, 255, 0.1)">
          <CardBody>
            <VStack spacing={6} align="stretch">
              <HStack spacing={4}>
                <Select
                  variant="filled"
                  value={month}
                  onChange={(e) => setMonth(parseInt(e.target.value))}
                  maxW="200px"
                  isDisabled={timesheet?.status === 'Submitted'}
                  color="white"
                >
                  {months.map((m, i) => (
                    <option key={i} value={i}>
                      {m}
                    </option>
                  ))}
                </Select>

                <Select
                  variant="filled"
                  value={year}
                  onChange={(e) => setYear(parseInt(e.target.value))}
                  maxW="150px"
                  isDisabled={timesheet?.status === 'Submitted'}
                  color="white"
                >
                  {[2024, 2025, 2026].map((y) => (
                    <option key={y} value={y}>
                      {y}
                    </option>
                  ))}
                </Select>
              </HStack>

              <Box overflowX="auto">
                <Table size="sm">
                  <Thead>
                    <Tr>
                      <Th>Date</Th>
                      <Th>Day</Th>
                      <Th>Type</Th>
                      <Th>Description</Th>
                    </Tr>
                  </Thead>
                  <Tbody>
                    {Array.from({ length: daysInMonth }, (_, i) => i + 1).map((day) => (
                      <Tr key={day} bg={isWeekend(day) ? 'rgba(255, 100, 100, 0.1)' : 'transparent'}>
                        <Td color="white">{day}</Td>
                        <Td>
                          <Text fontSize="sm" color={isWeekend(day) ? 'red.400' : 'whiteAlpha.900'}>
                            {getDayName(day)}
                          </Text>
                        </Td>
                        <Td>
                          <Select
                            variant="filled"
                            size="sm"
                            value={timesheet?.days[day]?.type || 'Full Day'}
                            onChange={(e) =>
                              handleDayTypeChange(day, e.target.value as TimesheetDayType)
                            }
                            isDisabled={timesheet?.status === 'Submitted'}
                            color="white"
                            bg="rgba(255, 255, 255, 0.05)"
                            cursor="pointer"
                            sx={{
                              '& select': {
                                cursor: 'pointer',
                              },
                            }}
                          >
                            <option value="Full Day">Full Day</option>
                            <option value="Half Day">Half Day</option>
                            <option value="Leave">Leave</option>
                          </Select>
                        </Td>
                        <Td>
                          <Textarea
                            variant="filled"
                            size="sm"
                            placeholder="What did you work on?"
                            value={timesheet?.days[day]?.description || ''}
                            onChange={(e) => handleDescriptionChange(day, e.target.value)}
                            isDisabled={timesheet?.status === 'Submitted'}
                            rows={2}
                            color="white"
                            bg="rgba(255, 255, 255, 0.05)"
                            resize="none"
                            sx={{
                              '&::placeholder': {
                                color: 'gray.500',
                              },
                            }}
                          />
                        </Td>
                      </Tr>
                    ))}
                  </Tbody>
                </Table>
              </Box>

              {timesheet?.status !== 'Submitted' && (
                <HStack spacing={4} justify="flex-end">
                  <Button
                    onClick={() => handleSave(false)}
                    isLoading={loading}
                    variant="outline"
                    color="whiteAlpha.900"
                    borderColor="rgba(255, 255, 255, 0.2)"
                    _hover={{ bg: 'rgba(255, 255, 255, 0.1)', borderColor: 'brand.400' }}
                  >
                    Save Draft
                  </Button>
                  <Button variant="gradient" onClick={() => handleSave(true)} isLoading={loading}>
                    Submit Timesheet
                  </Button>
                </HStack>
              )}
              {canUndoSubmission() && (
                <HStack spacing={4} justify="flex-end">
                  <Text fontSize="sm" color="yellow.400">
                    You can undo this submission within 7 days of month end
                  </Text>
                  <Button
                    onClick={handleUndoSubmission}
                    isLoading={loading}
                    colorScheme="yellow"
                    variant="outline"
                  >
                    Undo Submission
                  </Button>
                </HStack>
              )}
            </VStack>
          </CardBody>
        </Card>
      </VStack>
    </Layout>
  );
};

export default Timesheet;
